# Generated by Django 5.1.7 on 2026-02-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="name",
            field=models.TextField(
                default="Untitled", max_length=50, verbose_name="Name"
            ),
        ),
    ]
